# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blank #'Tübingen Women in Machine Learning'
email: tueml@gmail.com
description: > #this means to ignore newlines until "baseurl:" Women in Machine Learning Tübingen.
#baseurl:  # the subpath of your site, e.g. /blog
url: https://twiml.org # the base hostname & protocol for your site

# Gems
plugins: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/page:num/'
#markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll_video_tag

exclude:
  - Gemfile
  - Gemfile.lock
  - tmp/
  - vendo/
kramdown:
  input: GFM

menuitems:
    - { title:    Home,
        url:      /index.html }
    - { title:    About,
        url:      /about.html }
    - { title:    Contact,
        url:      /contact.html }
    - { title:     News,
        url:      /news.html}
   