# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll theme business casual
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  easy recipes to try at thome.
baseurl: "/jekyllthemeofbusinesscasual" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Gems
gems: [jekyll-paginate]

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/page:num/'